import os
import os.path
import re


def setPage(firstpage, basedir, increments):
    documents = os.listdir(basedir)
    page = firstpage
    for t in sorted(documents):
        if t == "_index.md":
            continue
        if t in increments:
            page += 1
        loc = os.path.join(basedir, t)
        content = ""
        with open(loc, "r") as f:
            content = f.read()
        content = content.replace("TODO", str(page))
        with open(loc, "w") as f:
            f.write(content)


def fixTraits():
    documents = os.listdir("tratti")
    content = ""
    for t in documents:
        loc = os.path.join("tratti", t)
        with open(loc, "r") as f:
            content = f.read()

        if "\ncategories: [" in content:
            print("skipped: " + loc)
            continue

        match = re.search(r"original-name: (.*)", content)
        if not match:
            print("skipped: " + loc)
            continue

        kinds = []
        for k, v in traitsData.items():
            if match.group(1) in v:
                kinds.append(k)

        content = content.replace(
            "\n---", "\ncategories: [" + ", ".join(kinds) + "]\n---"
        )
        with open(loc, "w") as f:
            f.write(content)


traitsData = {
    "generic": [
        "Archetype",
        "Attack",
        "Aura",
        "Cantrip",
        "Certain Kill",
        "Charm",
        "Circus",
        "Class",
        "Complex",
        "Concentrate",
        "Consecration",
        "Contingency",
        "Curse",
        "Darkness",
        "Death",
        "Dedication",
        "Detection",
        "Disease",
        "Downtime",
        "Emotion",
        "Exploration",
        "Extradimensional",
        "Fear",
        "Flourish",
        "Formian",
        "Fortune",
        "General",
        "Healing",
        "Ikeshti",
        "Incapacitation",
        "Incarnate",
        "Kaiju",
        "Legacy",
        "Light",
        "Lineage",
        "Linguistic",
        "Magical",
        "Manipulate",
        "Mental",
        "Metamagic",
        "Minion",
        "Misfortune",
        "Morph",
        "Move",
        "Multiclass",
        "Open",
        "Pervasive Magic",
        "Polymorph",
        "Possession",
        "Precious",
        "Prediction",
        "Press",
        "Radiation",
        "Reckless",
        "Revelation",
        "Scrying",
        "Secret",
        "Skill",
        "Sleep",
        "Spellshot",
        "Splash",
        "Stamina",
        "Summoned",
        "Telepathy",
        "Teleportation",
        "True Name",
        "Virulent",
        "Vocal",
    ],
    "alignment": ["Chaotic", "Evil", "Good", "Lawful"],
    "ancestry": [
        "Aasimar",
        "Anadi",
        "Android",
        "Aphorite",
        "Automaton",
        "Azarketi",
        "Beastkin",
        "Catfolk",
        "Changeling",
        "Conrasu",
        "Dhampir",
        "Duskwalker",
        "Dwarf",
        "Elf",
        "Fetchling",
        "Fleshwarp",
        "Ganzi",
        "Geniekin",
        "Gnoll",
        "Gnome",
        "Goblin",
        "Goloma",
        "Grippli",
        "Half-Elf",
        "Halfling",
        "Half-Orc",
        "Hobgoblin",
        "Human",
        "Ifrit",
        "Kitsune",
        "Kobold",
        "Leshy",
        "Lizardfolk",
        "Orc",
        "Oread",
        "Poppet",
        "Ratfolk",
        "Shisk",
        "Shoony",
        "Sprite",
        "Strix",
        "Suli",
        "Sylph",
        "Tengu",
        "Tiefling",
        "Undine",
    ],
    "armor": ["Bulwark", "Comfort", "Flexible", "Noisy"],
    "class": [
        "Alchemist",
        "Barbarian",
        "Bard",
        "Champion",
        "Cleric",
        "Druid",
        "Fighter",
        "Gunslinger",
        "Inventor",
        "Investigator",
        "Magus",
        "Monk",
        "Oracle",
        "Ranger",
        "Rogue",
        "Sorcerer",
        "Summoner",
        "Swashbuckler",
        "Witch",
        "Wizard",
    ],
    "class-specific": [
        "Additive",
        "Composition",
        "Cursebound",
        "Eidolon",
        "Evolution",
        "Finisher",
        "Hex",
        "Infused",
        "Instinct",
        "Litany",
        "Modification",
        "Oath",
        "Rage",
        "Social",
        "Stance",
        "Tandem",
        "Unstable",
        "Vigilante",
    ],
    "creature-type": [
        "Aberration",
        "Animal",
        "Astral",
        "Beast",
        "Celestial",
        "Construct",
        "Dragon",
        "Dream",
        "Elemental",
        "Ethereal",
        "Fey",
        "Fiend",
        "Fungus",
        "Giant",
        "Humanoid",
        "Monitor",
        "Negative",
        "Ooze",
        "Petitioner",
        "Plant",
        "Positive",
        "Spirit",
        "Time",
        "Undead",
    ],
    "elemental": ["Air", "Earth", "Fire", "Water"],
    "energy": [
        "Acid",
        "Cold",
        "Electricity",
        "Fire",
        "Force",
        "Negative",
        "Positive",
        "Sonic",
    ],
    "equipment": [
        "Adjustment",
        "Alchemical",
        "Apex",
        "Artifact",
        "Bomb",
        "Catalyst",
        "Clockwork",
        "Companion",
        "Consumable",
        "Contract",
        "Cursed",
        "Drug",
        "Elixir",
        "Focused",
        "Fulu",
        "Gadget",
        "Grimoire",
        "Intelligent",
        "Invested",
        "Mechanical",
        "Mutagen",
        "Oil",
        "Potion",
        "Saggorak",
        "Scroll",
        "Snare",
        "Spellheart",
        "Staff",
        "Steam",
        "Structure",
        "Talisman",
        "Tattoo",
        "Trap",
        "Wand",
    ],
    "hazard": ["Environmental", "Haunt", "Mechanical", "Trap"],
    "monster": [
        "Aasimar",
        "Acid",
        "Aeon",
        "Aesir",
        "Agathion",
        "Air",
        "Alchemical",
        "Amphibious",
        "Anadi",
        "Angel",
        "Anugobu",
        "Aquatic",
        "Arcane",
        "Archon",
        "Asura",
        "Azata",
        "Boggard",
        "Caligni",
        "Catfolk",
        "Changeling",
        "Charau-ka",
        "Clockwork",
        "Cold",
        "Couatl",
        "Daemon",
        "Demon",
        "Dero",
        "Devil",
        "Dhampir",
        "Dinosaur",
        "Div",
        "Drow",
        "Duergar",
        "Duskwalker",
        "Earth",
        "Electricity",
        "Fetchling",
        "Fire",
        "Genie",
        "Ghoran",
        "Ghost",
        "Ghoul",
        "Gnoll",
        "Golem",
        "Gremlin",
        "Grioth",
        "Grippli",
        "Hag",
        "Hantu",
        "Herald",
        "Ifrit",
        "Illusion",
        "Incorporeal",
        "Inevitable",
        "Kami",
        "Kobold",
        "Kovintus",
        "Leshy",
        "Lizardfolk",
        "Locathah",
        "Merfolk",
        "Mindless",
        "Morlock",
        "Mortic",
        "Mummy",
        "Munavri",
        "Mutant",
        "Nagaji",
        "Nymph",
        "Oni",
        "Orc",
        "Oread",
        "Paaridar",
        "Phantom",
        "Protean",
        "Psychopomp",
        "Qlippoth",
        "Rakshasa",
        "Ratfolk",
        "Sahkil",
        "Samsaran",
        "Sea Devil",
        "Serpentfolk",
        "Seugathi",
        "Shabti",
        "Siktempora",
        "Skeleton",
        "Skelm",
        "Skulk",
        "Sonic",
        "Soulbound",
        "Spriggan",
        "Sprite",
        "Stheno",
        "Suli",
        "Swarm",
        "Sylph",
        "Tane",
        "Tanggal",
        "Tengu",
        "Tiefling",
        "Titan",
        "Troll",
        "Troop",
        "Undine",
        "Urdefhan",
        "Vampire",
        "Vanara",
        "Velstrac",
        "Vishkanya",
        "Water",
        "Wayang",
        "Werecreature",
        "Wight",
        "Wraith",
        "Wyrwood",
        "Xulgath",
        "Zombie",
    ],
    "plane": [
        "Air",
        "Earth",
        "Erratic",
        "Finite",
        "Fire",
        "Flowing",
        "High Gravity",
        "Immeasurable",
        "Low Gravity",
        "Metamorphic",
        "Microgravity",
        "Negative",
        "Positive",
        "Sentient",
        "Shadow",
        "Static",
        "Strange Gravity",
        "Subjective Gravity",
        "Timeless",
        "Unbounded",
        "Water",
    ],
    "poison": ["Contact", "Ingested", "Inhaled", "Injury", "Poison"],
    "rarity": ["Common", "Rare", "Uncommon", "Unique"],
    "school": [
        "Abjuration",
        "Conjuration",
        "Divination",
        "Enchantment",
        "Evocation",
        "Illusion",
        "Necromancy",
        "Transmutation",
    ],
    "sense": ["Auditory", "Olfactory", "Visual"],
    "settlement": ["City", "Metropolis", "Town", "Village"],
    "tradition": ["Arcane", "Divine", "Occult", "Primal"],
    "weapon": [
        "Agile",
        "Attached",
        "Azarketi",
        "Backstabber",
        "Backswing",
        "Brutal",
        "Capacity",
        "Catfolk",
        "Climbing",
        "Cobbled",
        "Combination",
        "Concealable",
        "Concussive",
        "Conrasu",
        "Critical Fusion",
        "Deadly",
        "Disarm",
        "Double Barrel",
        "Dwarf",
        "Elf",
        "Fatal",
        "Fatal Aim",
        "Finesse",
        "Forceful",
        "Free-Hand",
        "Geniekin",
        "Gnome",
        "Goblin",
        "Grapple",
        "Halfling",
        "Hampering",
        "Injection",
        "Jousting",
        "Kickback",
        "Kobold",
        "Modular",
        "Monk",
        "Mounted",
        "Nonlethal",
        "Orc",
        "Parry",
        "Portable",
        "Propulsive",
        "Range",
        "Ranged Trip",
        "Reach",
        "Reload",
        "Repeating",
        "Resonant",
        "Scatter",
        "Shove",
        "Sweep",
        "Tethered",
        "Thrown",
        "Trip",
        "Twin",
        "Two-Hand",
        "Unarmed",
        "Versatile",
        "Volley",
    ],
}

if __name__ == "__main__":
    # fixTraits()
    setPage(
        618,
        "condizioni",
        [
            "collaborativo.md",
            "impreparato.md",
            "non-individuato.md",
            "pietrificato.md",
            "rotto.md",
        ],
    )
