name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: n1xx1/pfitdb-hugo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Hugo Build
        run: hugo mod get -u

      - name: Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add go.mod go.sum
          git commit -m "🚀 update pfitdb to $GITHUB_SHA"
          git push origin main
